name: CI

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]
  merge_group:

# You can leverage Vercel Remote Caching with Turbo to speed up your builds
# @link https://turborepo.org/docs/core-concepts/remote-caching#remote-caching-on-vercel-builds
# env:
#  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
#  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  build-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Remove the Copy env step if you don't need .env.local
      # - name: Copy env
      #   shell: bash
      #   run: cp .env.example .env.local

      - name: Setup bun
        uses: oven-sh/setup-bun@v1

      - name: Install lib
        run: bun i

      - name: Build
        run: bun run build
        env:
          NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}

      - name: lint and type-check
        run: bun run lint format typecheck
